name: social_media_app
description: A social media app using Flutter, Dart, GetX, and REST API that allows users to share their photos and videos.

publish_to: "none"

version: 1.0.1+31

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3
  geolocator: ^9.0.2
  geocoding: ^2.1.0

  talker_flutter: ^2.4.3

  flutter_svg: ^2.0.4
  image_picker: ^0.8.7+1
  image_cropper: ^3.0.2
  photo_view: ^0.14.0
  cached_network_image: ^3.2.3
  flutter_carousel_widget: ^2.0.2

  flutter_animate: ^4.1.1+1
  rive: ^0.10.3

  connectivity_plus: ^3.0.3
  http: ^0.13.5
  intl: ^0.18.0
  get_time_ago: ^1.2.2

  cloudinary: ^1.1.1
  r_upgrade: ^0.4.2

  libsignal_protocol_dart: ^0.6.5

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  url_launcher: ^6.1.10
  flutter_linkify: ^5.0.2
  share_plus: ^6.3.1

  flutter_local_notifications: ^13.0.0
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0

  better_player: ^0.0.83
  emoji_picker_flutter: ^1.5.2
  path: ^1.8.2
  file_picker: ^5.2.6
  path_provider: ^2.0.14
  flutter_markdown: ^0.6.14
  flutter_image_compress: ^1.1.3
  video_compress_ds: ^3.1.6

  flutter_screenutil: ^5.7.0
  permission_handler: ^10.2.0
  flutter_datetime_picker: ^1.5.1

  get: ^4.6.5
  get_storage: ^2.1.1
  built_value: ^8.4.4
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  copy_with_extension: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.19

  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1
  copy_with_extension_gen: ^5.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/rive/
    - assets/svgs/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Muge
      fonts:
        - asset: assets/fonts/MugeRegular.ttf
