name: social_media_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  device_info_plus: ^3.2.3

  image_picker: ^0.8.5
  image_cropper: ^2.0.0
  cached_network_image: ^3.2.0
  photo_view: ^0.13.0
  flutter_carousel_widget: ^1.0.5

  connectivity: ^3.0.6
  http: ^0.13.4
  intl: ^0.17.0
  get_time_ago: ^1.1.3

  flutter_screenutil: ^5.5.1
  permission_handler: ^9.2.0
  pattern_formatter: ^2.0.0
  flutter_datetime_picker: ^1.5.1
  country_code_picker: ^2.0.2

  get: ^4.6.1
  get_storage: ^2.0.3
  built_value: ^8.2.3
  json_annotation: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.6

  build_runner: ^2.1.10
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/
