name: Flutter CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build APK and Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.5'
      - run: flutter pub get
      - run: flutter build apk --dart-define=CLOUDINARY_CLOUD_NAME=${{secrets.CLOUDINARY_CLOUD_NAME}} --dart-define=CLOUDINARY_UPLOAD_PRESET=${{secrets.CLOUDINARY_UPLOAD_PRESET}} --split-per-abi --obfuscate
      - name: Create a Release in GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab"
          token: ${{ secrets.GH_BUILD_TOKEN }}
          tag: v1.0.0-beta.${{ github.run_number }}
          commit: ${{ github.sha }}